# Training config ()
defaults:
  # "cifar10" or "stl10"
  - dataset: cifar10
  # "sgd" or "adam" or "radam" or "lars"
  - optimizer: sgd
  # "cosine" or "multi_step" or "cosine_annealing" or "none"
  - lr_sheduler: cosine
  # "resnet" or "sk_resnet"
  - encoder: resnet
  # "moco" or "simclr" or "swav" or "byol" or "simsiam" or "deepclusterv2" or "barlow_twins" or "ressl"
  - self_supervised: ressl

experiment_params:
  debug_mode: true
  run_name  : sample9
  seed      : 0              # (default: None)
  output_dir: output/sample

train_params:
  # common params
  gpu_id       : 0
  multi_cpu_num: 32
  epoch_num    : 300
  batch_size   : 512
  use_amp      : true

  log_interval:
    train      : 1    # epoch
    validation : 10   # epoch
    checkpoints: 10   # epoch

  resume:               # 学習を再開したい場合は，下記を指定
    use        : false  # falseの場合は再開しない
    run_name   :        # 再開したいtrain/run_nameを指定(default: None)
    checkpoints:        # epochを指定する(default: None)

hydra:
  run:
    dir: ./${experiment_params.output_dir}/hydra
