multi_view_list: [base, base]  # query and key

views:
    ## augmentation sample https://pystyle.info/pytorch-list-of-transforms/#outline__6_9
    #  """
    #SimCLR-v1:[
    #random_resize_crop: always, scale=[0.08, 1.0]
    #color_jitter      : p=0.8, brightness=0.8, contrast=0.8, saturation=0.8, hue=0.2
    #gaussian_blur     : p=0.5, sigma=[0.1, 0.2]
    #gary_scale        : p=0.2
    #horizontal_flip   : p=0.5
    #]
    #SimCLR-v2: Same as SimCLR-v1
    #"""
    base:  # query and key
        random_resize_crop:
            use: true
            root: torchvision.transforms
            name: RandomResizedCrop
            params:
                size: 32
                scale: [ 0.08, 1.0 ]
                ratio: [ 0.75, 1.333 ]

        color_jitter:
            use: true
            root: util_augments
            name: RandomColorJitter
            params:
                brightness: 0.8
                contrast: 0.8
                saturation: 0.8
                hue: 0.2
                p: 0.8

        gary_scale:
            use: true
            root: torchvision.transforms
            name: RandomGrayscale
            params:
                p: 0.2

        gaussian_blur:
            use: false
            root: util_augments
            name: RandomGaussianBlur
            params:
                sigma: [ 0.1, 0.2 ]
                p: 0.2

        horizontal_flip:
            use: true
            root: torchvision.transforms
            name: RandomHorizontalFlip
            params:
                p: 0.5

